title: e^2 Projects
theme: jekyll-theme-cayman 
author: Peter
email: donnelpicasso@gmail.com
description: Portfolio of electrical& computer engineering projects
github_username: peterjfk

markdown: kramdown
